[font]
size = 14

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[general]
import = [ "/usr/lib/node_modules/alacritty-themes/themes/Wombat.toml" ]
