add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"


[env_var.SHELL]
variable = 'SHELL'
default = 'unknown shell'

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
repo_root_style = "bold cyan"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
home_symbol = "/home/hchinchilla"

[git_branch]
format = "[$branch]($style) "
style = "italic yellow bold"

[git_status]
disabled   = true
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
