# Solves crackling sound while CPU is bussy during a Google Meet

context.properties = {
    default.clock.quantum     = 2048
    default.clock.min-quantum = 1024
    default.clock.max-quantum = 8192
}
