# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
#env = GDK_SCALE,2
#monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.6

# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1
monitor=eDP-1,preferred,auto,1.2
#monitor=DP-2,2560x1440,auto,1
monitor=desc:California Institute of Technology 0x1309, 3000x2000, auto, 2 # Huawei Matebook eDP-1
monitor=desc:Dell Inc. DELL U2721DE 8VWVQ83, 2560x1440, 0x0, 1
monitor=desc:Dell Inc. DELL U2719D 1DWLX13, 2560x1440, 2560x-700, 1, transform, 1
monitor=desc:Dell Inc. DELL U2713HM GK0KD345A4GL, 2560x1440, -2560x0, 1 # Monitor Casa Jordi

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2
